version: '3'

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - MONGO_URL=mongodb://mongo:27017/netflix-clone
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - '3000:3000'

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=netflix-clone
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - '6379:6379'

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
